### ISSUE TITLE
Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by ciureaalex** [draconar/grab_packt#15]
When I runned the "run.bat" file to test if this thing it's working I got this error:

`
C:\Users\Administrator\Documents\GitHub\grab_packt>run.bat
module.js:327
throw err;
^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename module.js:325:15
    at Function.Module._load module.js:276:25
   at Module.require module.js:353:17
   at require <internal/module.js:12:17>
   at Object.<anonymous> <C:\Users\Administrator\Documents\GitHub\gran_pack\Server.js:1:63>
   at Module._compile module.js:409:26
   at Object.Module._extensions..js module.js:416:10
   at Module.load module.js:343:32
   at Function.Module._load module.js:441:10

C:\Users\Administrator\Documents\GitHub\grab_packt>
`
And that's all, output.txt it's also empty.

OS Information: Windows Server 2008 R2 Datacenter, Build 7601, x64, SP1
Node.js Information: MSI Installer, Current version: v4.4.7 (includes npm 2.15.8), nothing special done to it, just next, next, next, finish.

Any help?

**Comment by Plloi** [comment]
Did you run `npm install` in the grab_packt directory?

**Comment by akashchitlangia** [comment]
Please run this command 

![image](https://user-images.githubusercontent.com/4955355/37655310-ea669610-2c6a-11e8-96e5-d676618dac34.png)
