### ISSUE TITLE
Packtpub paused the daily deals

### ISSUE THREAD

**Issue by BetaUliansyah** [draconar/grab_packt#16]
Got this email several hours ago:

> Whilst we finish getting ready for the reveal, we've temporarily paused Deal of the Day. Instead, every day we're giving you the chance to claim some free eBooks and today's free titles are all about web development.

And they are adding captcha in unregistered access. 

I cant find the list of download links in this new free download program. I think it can only available from email they send.

**Comment by BetaUliansyah** [comment]
The daily deals still continues, while the free ebooks offers from their email is going on also.

**Comment by draconar** [comment]
Hi @BetaUliansyah is the promotion still going? Should I updated anything to the code?
