### ISSUE TITLE
Project just became obsolete

### ISSUE THREAD

**Issue by jrial** [draconar/grab_packt#19]
Since yesterday, Packt has stopped offering the free eBook of the day as part of their free learning programme. As of now, the same URL displays a page where you can sign up for the new deal: 10 days of free access to their entire catalog. As such, this software is no longer functional. I guess it would be best to update the README to reflect this.

Thanks for creating this. It was much appreciated.

**Comment by Plloi** [comment]
Weird yesterday there was a notice saying free eBooks would restart in january, but it's gone now...

**Comment by jrial** [comment]
@Plloi oh, didn't check yesterday, so I assumed it was permanent.

Will keep issue open for now (unless @draconar wants to close it), so people who come check the issues after noticing their cron jobs failing know what's going on. Setting a reminder for Jan. 6 to come close this issue.

**Comment by jspraul** [comment]
Here is a screenshot of the notice:

![20161219-packtpub-free-learning](https://cloud.githubusercontent.com/assets/115931/21332024/ca475d60-c613-11e6-91af-67d257fd56da.png)

Free books are still listed daily on Twitter (https://twitter.com/PacktPub), eg:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Get started in the world of <a href="https://twitter.com/hashtag/Docker?src=hash">#Docker</a> with today&#39;s free title! <a href="https://t.co/7QnEw6Xvmm">https://t.co/7QnEw6Xvmm</a> <a href="https://t.co/MFIXULbRPr">pic.twitter.com/MFIXULbRPr</a></p>&mdash; Packt (@PacktPub) <a href="https://twitter.com/PacktPub/status/810824519661322240">December 19, 2016</a></blockquote>

They link to a unique (giant) url daily, eg:

https://www.packtpub.com/packt/free-ebook/what-you-need-know-about-docker2

Not sure what the timelines are on how long the url is valid, etc.

**Comment by jrial** [comment]
Reminder went off to close this issue. But the free ebook page hasn't returned yet. I postponed my reminder for another week, and will keep doing so until the page is back or I get bored with the whole affair.

If anyone else feels this issue can be closed already, feel free. I think anyone who was wondering what was going on and had the common sense to check the bug reports has done so already.

**Comment by draconar** [comment]
Hi Guys, sorry for leaving you alone in here. I've been moving from 1 country to other. 

As we stand today. What is the current status of this situation? Is the project standing still or something must change? 

May I close this issue?

**Comment by jrial** [comment]
The eBooks are back. I'm no longer getting any errors from my cron mail, so I'm closing the issue.
