### ISSUE TITLE
More Accurate Crontab Hour

### ISSUE THREAD

**Issue by BetaUliansyah** [draconar/grab_packt#9]
I think the correct hour in crontab is `25 0 * * *`, if you are using UTC/BST timezone in your server. I have compared `date` output with countdown clock in packt's website, and conclude this solution.

Here is my crontab settings:
`25 0 * * * /usr/bin/nodejs /home/user/grab_packt/server.js >> /tmp/cron_output`

**Comment by draconar** [comment]
hi beta, wanna create a pull-request, so I can merge the information?

**Comment by BetaUliansyah** [comment]
done
